// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChSgqgFcik35s2xxeKxFBrAFOhkhySM00',
    appId: '1:421168839378:android:90320860797e9ee5714b0b',
    messagingSenderId: '421168839378',
    projectId: 'palvi-agrico-6e36d',
    databaseURL: 'https://palvi-agrico-6e36d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'palvi-agrico-6e36d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQwt2JUYY0viL23H_xVbRulvj6XQk16MU',
    appId: '1:421168839378:ios:9d79b58df1e3596c714b0b',
    messagingSenderId: '421168839378',
    projectId: 'palvi-agrico-6e36d',
    databaseURL: 'https://palvi-agrico-6e36d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'palvi-agrico-6e36d.firebasestorage.app',
    iosClientId: '421168839378-iqmccr0qrms1c0fgf8s923t2oatobjjh.apps.googleusercontent.com',
    iosBundleId: 'com.pt.palviagrico',
  );
}
